### PR TITLE
take care of the case when sdk may be null inside getSearchPath()

### PR DESCRIPTION
**Pull request by omerjerk**
Signed-off-by: Umair Khan <omerjerk@gmail.com>

### CODE REVIEW

**Comment by codeanticode** [comment]
doesn't sound like a good solution. @Manindra29 do you know a better fix is possible to address the threading issues?

**Comment by omerjerk** [comment]
I just had a look at the code again.
This is certainly not a good solution.
I'm just not able to get why was the SDK null at all. SDK is loaded on the main thread itself.
The `checkSDK()` function is called from the constructor of `AndroidEditor` class [here](https://github.com/processing/processing-android/blob/master/src/processing/mode/android/AndroidEditor.java#L139).
All the instructions of `AndroidMode.checkSDK()` method are executed on the main thread only.
It means, when the Editor is created we should never have a null sdk.

**Comment by omerjerk** [comment]
Oh, and if the path of SDK has been saved inside the Preferences once, AndoridMode will always be able to load the SDK during all the subsequent runs.

**Comment by Manindra29** [comment]
No, this is not a good solution. I've submitted a better solution here https://github.com/processing/processing-android/pull/143

**Comment by omerjerk** [comment]
I also faced a situation when getSearchPath was called and sdk was not null but PDE still red lined the android.view.* import.
Just confirming, are you sure that returning the path of jar file must solve this issue ?

**Comment by Manindra29** [comment]
Oh yes, when I was taking a deeper dive, I realised that the new searchPath will need to be used at two places: ErrorCheckerService's classpath (which underlines errors) and ASTGenerator's classpath (which is responsible for auto complete). I've yet to get to updating ECS' classpath.

**Comment by omerjerk** [comment]
@Manindra29 
Cool. Just notify here whenever your fix is ready. I'll test the android mdoe.

**Pull request closed without merging**
