### PR TITLE
[ENHANCE] GUI to set VR type - daydream or cardboard

### LINKED ISSUE #381: VR sketches need manual edit of manifest file to work on Daydream headsets
Android mode sets the com.google.intent.category.CARDBOARD category by default, and com.google.intent.category.DAYDREAM is required for the sketch to be compatible with Daydream headsets. Right now, the only workaround is to set the correct category manually by editing the manifest file. [Forum discussion](https://forum.processing.org/two/discussion/comment/102118/). Perhaps an option could be added to the preferences file to pick between cardboard and daydream.

### PR DESCRIPTION
**Pull request by SyamSundarKirubakaran**
fixes #381

screen shot 2018-09-09 at 8 35 28 am

Signed by : @SyamSundarKirubakaran

### CODE REVIEW

**Comment by codeanticode** [comment]
Awesome, thank you! I will revising and merging soon!

**Comment by codeanticode** [comment]
@SyamSundarKirubakaran there is no way to autodetect if the headset is cardobard or daydream right?

**Comment by SyamSundarKirubakaran** [comment]
@codeanticode yes, I don't think we have a mechanism to detect if it's a Daydream or Cardboard automatically - even if there is a way to get it, Manifest files can't be changed once an instance  of an app is created so I guess this is the better way of doing it. But what I do know is that the Daydream works only with the `STEREO` and not with the `MONO` renderer.

**Comment by codeanticode** [comment]
@SyamSundarKirubakaran took me some time to merge it, but finally got to do it. Thank you for this PR!

**Comment by Calsign** [comment]
@SyamSundarKirubakaran @codeanticode I realize that I'm a bit late to this PR, but I think there is an easier way to support both cardoard and daydream. An intent filter can specify more than one category: see [how I did this in APDE](https://github.com/Calsign/APDE/blob/master/APDE/src/main/assets/templates/VRManifest.xml.tmpl#L24). (I have tested with both headsets.)

You don't need this, or any of the requisite changes:

```xml
<category android:name="@@vr_type@@" />
```

...because you can just do this:

```xml
<category android:name="com.google.intent.category.CARDBOARD" />
<category android:name="com.google.intent.category.DAYDREAM" />
```

I think there are potential benefits to specifying the target headset - for example, if we had a library for interacting with the hardware buttons on daydream that didn't support cardboard, then selecting the target headset could decide whether or not to package the library into the sketch - but we don't have that at the moment (and I think that such a library should be compatible with both cardboard and daydream anyway).

It seems to me that this solution forces the user to take an extra step when that is not necessary while complicating the code base when the same functionality could be achieved with a single line of code. Unless I'm missing something, that is.

**Comment by codeanticode** [comment]
@Calsign thanks a lot for bringing this up. I'd definitely prefer not to have the extra Daydream/Cardboard menu, and so if the intent approach works, I'd go with that. I don't have a Daydream headset to test it though. @SyamSundarKirubakaran do you have any comments on this?

**Comment by SyamSundarKirubakaran** [comment]
@Calsign yeah right, I didn't think that through.! I thought giving the control to the user fore-handed would be nice.! But yeah, this is a go for me as well.! 

> I think there are potential benefits to specifying the target headset - for example, if we had a library for interacting with the hardware buttons on daydream that didn't support cardboard, then selecting the target headset could decide whether or not to package the library into the sketch - but we don't have that at the moment (and I think that such a library should be compatible with both cardboard and daydream anyway).

Agreed.!

**Pull request merged**
