### PR TITLE
Add support of Kotlin/Native and Upgrade Gradle Build System to Kotlin DSL in processing-android

### PR DESCRIPTION
**Pull request by ranaaditya**
- [x] **Add support of Kotlin in the project**
- [x] **Migrate AR, VR, Core library from Java to Kotlin** 
- [x] **Upgrade Groovy based Gradle to Kotlin DSL based Gradle Build System**
- [x] **Refactor the codebase**
- [x] **Implement migrated code on JVM**
- [x] **Solve some renderer issues**

An outcome of : **_Google Summer of Code 2020_**
Author : Aditya Rana @ranaaditya
Mentor : Syam Sundar K @SyamSundarKirubakaran

### CODE REVIEW

**Comment by ranaaditya** [comment]
@codeanticode can you review this PR

**Comment by codeanticode** [comment]
@ranaaditya thanks so much for all this great work! I will review ASAP!

**Comment by codeanticode** [comment]
@ranaaditya again this is very cool, but with so many changes introduced in a single PR I'm wondering if this contrib could be broken up in smaller pieces. For example, support for Kotlin sketches on one hand, and Kotlin rewrite of the mode itself on the other. I'm curious to known what was the motivation to rewrite the mode in Kotlin, is that required for Kotlin support in the sketches? Also, would these changes enable using Kotlin Native? According to some [earlier conversations](https://github.com/processing/processing/wiki/Project-List#-support-for-kotlin-native), sounded like Kotlin Native could allow running Processing sketches on Android and iOS

**Comment by ranaaditya** [comment]
> @ranaaditya again this is very cool, but with so many changes introduced in a single PR I'm wondering if this contrib could be broken up in smaller pieces. For example, support for Kotlin sketches on one hand, and Kotlin rewrite of the mode itself on the other. I'm curious to known what was the motivation to rewrite the mode in Kotlin, is that required for Kotlin support in the sketches? Also, would these changes enable using Kotlin Native? According to some [earlier conversations](https://github.com/processing/processing/wiki/Project-List#-support-for-kotlin-native), sounded like Kotlin Native could allow running Processing sketches on Android and iOS


Hi @codeanticode ,

### **Can we break up this PR into smaller pieces and is it necessary to rewrite mode into kotlin ?**

Yes, we can break this PR into number smaller pieces like one for mode, AR library, VR library, Core.

Actually I did this whole work in smaller pieces only. I started with mode then AR-library then VR-library and then Core and finally I upgraded the build system to Kotlin DSL and added support for Kotlin-documentation Engine.

I have separate branches for every specific change that I made in my Final PR.

I branched out to these branches in  respective manner (AR-migration will be having Mode-migration commits and so on)

For **Mode Migration**- https://github.com/ranaaditya/processing-android/commits/GSoC20_p1_mode

For **AR-library Migration** -  https://github.com/ranaaditya/processing-android/commits/GSoC20_ar_migration

For **VR-library Migration** - https://github.com/ranaaditya/processing-android/commits/GSoC20_vr_migration

For **Core Migration** - https://github.com/ranaaditya/processing-android/commits/GSoc20_core_api_migration

For **build-system upgradation** - https://github.com/ranaaditya/processing-android/commits/GSoc20_kts_dsl

For **kotlin-documentation generation** - https://github.com/ranaaditya/processing-android/tree/GSoc20_dokka

For **upgrading the inbuilt plugin** - https://github.com/ranaaditya/processing-android/commits/GSoc20_aar_plugin

**Final working branch** which has some fixes and other updates required to run processing successfully - https://github.com/ranaaditya/processing-android/tree/Kotlin-Native 

**I made Single PR because while I was Migrating the codebase to kotlin it was hard to avoid code breaking and other runtime errors due to slight changes in Inheritance models of both languages.** 

But Final PR has no errors/issues as I have tested it on more than 100 sketches and especially run all processing API given on official website -https://processing.org/reference/

### **processing-core Jar file for My migrated work can be found here** - http://bit.ly/processing-kotlin-jar 

### **What was the motivation to rewrite the mode in Kotlin**

After discussing a lot with with Syam Sundar (mentor) and facing runtime errors without Migration We reached to point that its needed to Migrate mode as well !

Migration was backed by few notable points:

1. Java supports nullable type only but Kotlin has option to support either nullable or  non-nullable types and we can't intermix i.e. for nullable parameters ina afunction, kotlin value need to be of nullable  type, if you try to pass non-nullable type you will be trapped in runtime errors !

2. And importantly - **Kotlin has different compiling architecture as compared to Java**.

**Java directly converts code into bytecode but Kotlin has 2 steps Compiling Architecture - Kotlin -> IR -> bytecode this is where Kotlin/Native comes in power, we can use these IR (Intermediate Representation) for our iOS implementation code.**

### **Would these changes enable using Kotlin Native ?**
yes these changes would definetly enable Kotlin/native support in processing-android.

### **sounded like Kotlin Native could allow running Processing sketches on Android and iOS**
Yes Kotlin/Native is able to run on both Android as well as on iOS.
I have implemented Processing API on JVM with kotlin native, and its working fine for Android as I have tested very rigorously for real devices of different specifications from very high end devices (latest Android phones with Android Pie) to very low end devices ( with Android Kitkat and having very low RAM).

regards,
Aditya Rana

**Comment by codeanticode** [comment]
@ranaaditya please recreate this PR int the [forked processing-android repo](https://github.com/codeanticode/processing-android/) which will then become processing-kotlin-native.

**Comment by ranaaditya** [comment]
Hi Everyone, this PR has been closed and came out to be an independent project and hosted [here](https://github.com/processing-for-kotlin/kotlin-native-mode).

Thanks to @SyamSundarKirubakaran and  @codeanticode for their amazing support !

Thanks everyone who involved in the discussion here.

Thank you !

**Pull request closed without merging**
