### PR TITLE
Added open and close functionality of Soft keyboard

### LINKED ISSUE #297: Add open/closeKeyboard() function to PApplet?
Right now there is no way, unless using the Android API, to open and close the soft keyboard.

### PR DESCRIPTION
**Pull request by gunkiratk**
Closed #297

### CODE REVIEW

**Comment by omerjerk** [comment]
Looks good to me.

**Comment by codeanticode** [comment]
@gunkiratk @gunkiratk 

[openKeyboard()](https://github.com/processing/processing-android/blob/multitouch/core/src/processing/core/PApplet.java#L2409) and [closeKeyboard()](https://github.com/processing/processing-android/blob/multitouch/core/src/processing/core/PApplet.java#L2417) are already included in PApplet. In what way are the ones proposed in this PR are different and/or better?

**Comment by gunkiratk** [comment]
@codeanticode When we cloned the repo ,both the functions were not included.
So we implemented them.

**Comment by codeanticode** [comment]
Ok, got it. Looks like the only difference is that in the current code I'm using the InputMethodManager .showSoftInput/hideSoftInputFromWindow methods, which require an additional reference to the root view, whereas in your PR you call InputMethodManager.toggleSoftInput(), which does not need the view. Any advantage of one over the other?

**Comment by gunkiratk** [comment]
@codeanticode The only one advantage I found is showSoftInput() does not work when device has a hard (slide-out) keyboard whereas toggleSoftInput() works for every device.

**Comment by codeanticode** [comment]
@gunkiratk Great observation, removed old code and merged your PR. Thank you!

**Comment by codeanticode** [comment]
@gunkiratk Actually, I just thought that if you have a hardware keyboard, you might not want the soft keyboard to open up, since you will be receiving the key events from hard keyboard anyways, wouldn't you agree?

**Comment by gunkiratk** [comment]
But I think we should give an option of softKeyboard to users with hardware keyboard ,just like laptops and PCs with hard keyboard have, because there can be possibility the hardware keyboard is not working or some keys are not functional then the user can use softKeyboard.So it is better to use toggleSoftInput() as it works with all devices.

**Pull request merged**
