### PR TITLE
remove RTE from glDrawBuffer/glReadBuffer

### PR DESCRIPTION
**Pull request by omerjerk**
Signed-off-by: Umair Khan <omerjerk@gmail.com>

### CODE REVIEW

**Comment by omerjerk** [comment]
After applying this commit, I'm able run my video library properly.
Other users have also reported the error caused by the call to these two functions. I'll add a link to them here shortly.

**Comment by codeanticode** [comment]
I don't see you are using glDrawBuffer/glReadBuffer anywhere in the video library, except in [this line](https://github.com/omerjerk/processing-video-android/blob/f719c4c255784243c4efc30c589b49b18c7de392/src/in/omerjerk/processing/video/android/VideoBase.java#L138), which is commented out anyways. How does this PR make the library run properly?

**Comment by codeanticode** [comment]
ok, got it, the renderer uses readBuffer and drawBuffer in several places.

**Comment by omerjerk** [comment]
Hi @codeanticode,
I was thinking if this might create other problems. What if the user tries to call pgl.glDrawBuffer() ?
I'm not so sure if this a correct of way.

**Pull request merged**
