### PR TITLE
[WIP] make compatible with the new processing APIs

### PR DESCRIPTION
**Pull request by omerjerk**
Signed-off-by: Umair Khan <omerjerk@gmail.com>

Android mode is still not being shown inside the mode drop down list. No idea why. Is there something special to be done ?

### CODE REVIEW

**Comment by omerjerk** [comment]
can anyone help me to write what should go here ? - https://github.com/processing/processing-android/pull/98/files#diff-2288076d35b39dac135cf3285174cbedR56

I had a look at the corresponding method inside the `JavaToolbar` class but still couldn't figure it out.

**Comment by omerjerk** [comment]
@benfry Can you please help me with this ?

**Comment by benfry** [comment]
Still working on it, sorry. The APIs aren't ready to go yet.

**Comment by omerjerk** [comment]
As of now the Android Mode is building and running sketches on the device. I'm not sure if it's a good thing to add all the jar dependencies here itself. Any comments here would be really helpful.

**Comment by benfry** [comment]
Thanks for looking into this. 

Unless we're going to complete untangle Android Mode from Java Mode (which we probably should, eventually), let's just use the JARs from Java Mode, instead of re-adding them here.

**Comment by omerjerk** [comment]
I second that. But I was not able to run AndroidMode without adding these JARs. That's why I asked in my last comment about adding these JARs.

**Comment by benfry** [comment]
So what's not working with referencing the jars from Java Mode? Is it a runtime problem that the class loader cannot find them, or a build problem?

**Pull request closed without merging**
