### PR TITLE
Core AndroidX support and creation of distributions for JCentre  

### PR DESCRIPTION
**Pull request by rupesh-kumar-lpu**
The PR adds the creation of AndroidX distributions for android processing core. It is the initiation of migrating Android Mode and PDE to use AndroidX build. The PR will not intervene in the Android Mode in any way. Gradle build in the root directory will be creating the following distributions -

- core-androidx/dist/processing-core-androidx-1.1.1.jar
- core-androidx/dist/processing-core-androidx-1.1.1.jar.md5
- core-androidx/dist/processing-core-androidx-1.1.1.pom
- core-androidx/dist/processing-core-androidx-1.1.1-sources.jar

Some of the AndroidX variables are defined in `mode/version.properties` and `mode/mode.properties` to use in `build.gradle` and `core-androidx/build.gradle` files. The directory `core-androidx/src/assets` remains same as `core/src/assets`. 
An [Example](https://github.com/rupesh-kumar-lpu/Processing-AndroidX-Sample) androidx project shows the use of `core-androidx/dist/processing-core-androidx-1.1.1.jar`. with the latest platform target API Level 30.
For now, the current PR does not include any code to copy zip in Android Mode nor it includes code to publish distributions. Some TODO tasks are defined in the core-androidx/build.gradle file.

### CODE REVIEW

**Comment by rupesh-kumar-lpu** [comment]
@codeanticode If you would like to review? Will it be better to include AndroidX for android mode and PDE? I think there is no support for android support libraries after Android Platform 28.

**Comment by codeanticode** [comment]
@rupesh-kumar-lpu Hi Rupesh, thanks a lot for your contribution! I just started doing some belated work on the AndroidX port in [this branch](https://github.com/processing/processing-android/tree/androidx). I will now review your PR, however, after a cursory glance looks like you have created a separate version for the core library using the AndroidX libraries, is that right? I'd rather have a single version for maintenance reasons. If that's the case, we should still be able to run Processing sketches on devices running older versions of Android, shouldn't we?

**Comment by rupesh-kumar-lpu** [comment]
@codeanticode You are right I was into providing a separate version for the AndroidX library. Good to know that the work is already in progress in another branch. I totally agree with your point that It is good to have a single version of android support for now in master. It will be better not to merge this request. Thanks!

**Comment by rupesh-kumar-lpu** [comment]
reverted the wrong commits to the forked master branch in case the request will be reviewed

**Pull request merged**
